//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Station.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
namespace ITS.Domain.Entities
{
    public class BusStation
    {
        /// <summary></summary>
        public Guid ID;
        public Guid RoadSessionID;
        /// <summary></summary>
        public String StationName;
        /// <summary></summary>
        public string Position;
        /// <summary></summary>
        public string GetRoadName()
        {
            return string.Empty;
        }
    }
}
