//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Station.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
namespace ITS.Domain.Entities
{
    public class BusStation
    {
        public Guid ID;
        public Guid RoadSessionID;
        public String StationName;
        public float Position_X;
        public float Position_Y;
    }
}
