//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Movement.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
namespace ITS.Domain.Entities
{
    public class BusMovement
    {
        public Guid ID { get; set; }
        public Guid BusStationFrom { get; set; }
        public Guid BusStationTo { get; set; }
        public bool Direction;
        /// <summary></summary>
        public int OrderNumber;
    }

}