//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : IntermediatePoint.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
namespace ITS.Domain.Entities
{
    public class IntermediatePoint
    {
        /// <summary></summary>
        public Guid ID;
        /// <summary></summary>
        public string Position;
    }

}