//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : IntermediatePoint.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
namespace ITS.Domain.Entities
{
    public class IntermediatePoint
    {
        public Guid ID { get; set; }
        public Guid BusMovementID { get; set; }
        public float lat { get; set; }
        public float lng { get; set; }
        public int OrderNumber { get; set; }
    }

}