//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Movement.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
namespace ITS.Domain.Entities
{
    public class Movement
    {
        /// <summary></summary>
        public bool Direction;
        /// <summary></summary>
        public int OrderNumber;
    }

}