//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : RoadSession.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
using ITS.Domain.Entities.Extensions;
namespace ITS.Domain.Entities
{
    public class RoadSession
    {
        /// <summary></summary>
        public Guid ID;
        public Guid RoadID;
        /// <summary></summary>
        public int AddressLower;
        /// <summary></summary>
        public int AddressUpper;
        /// <summary></summary>
        public String Description;
        /// <summary></summary>
        public Point PositionLower { get; set; }
        public Point PositionUpper { get; set; }
    }
}