//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Road.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
namespace ITS.Domain.Entities
{
    public class Road
    {
        /// <summary></summary>
        public Guid RoadID;
        /// <summary></summary>
        public String RoadName;
    }
}