//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Route.cs
//  @ Date : 27/11/2011
//  @ Author : 
//
//


/// <summary></summary>
/// <summary></summary>
using System;
namespace ITS.Domain.Entities
{
    public class BusRoute
    {
        /// <summary></summary>
        public Guid RouteID;
        /// <summary></summary>
        public String RouteName;
    }
}